//
//  AMerchantCFG.h
//  PopulationTest
//
//  Created by Serious Games on 17/6/13.
//
//

#ifndef PopulationTest_AMerchantCFG_h
#define PopulationTest_AMerchantCFG_h

std::string amerchantDefaults =
"{\"name\":\"root\","
"\"default_happiness\":\"50\","
"\"default_money\":\"1000\","
"\"default_loyalty\":\"50\","
"\"default_education_level\":\"1\","
"\"default_move_range\":\"20\","
"\"default_intelligence\":\"50\","
"\"default_social\":\"50\","
"\"default_energy\":\"100\","
"\"default_exp_level1\":\"100\","
"\"default_exp_level2\":\"120\","
"\"default_exp_level3\":\"140\","
"\"default_exp_level4\":\"160\","
"\"default_exp_level5\":\"0\","
"\"spawn_cost\":\"500\""
"}";

std::string amerchantRequirements =
"{\"name\":\"citizen\","
"\"required_loyalty\":\"50\","
"\"required_education_level\":\"1\","
"\"required_intelligence\":\"50\","
"\"required_social\":\"50\""
"}";



std::string amerchantConfig =
"{\"name\":\"root\","
"\"type\":\"sequence\","
"\"items\":"

// 1st item - Need to get a House

"[{"
"\"name\":\"I need a Home\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"I don't have a house?\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"hasNoHouse\""
"},"
"{"
"\"name\":\"Find a House\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"buyVacantHouse\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"buyVacantHouse\""

"},"
"{"
"\"name\":\"No House!\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"gotNoHouseWarning\""
"}]"
"}]"
"},"

// 2nd item - the Need to do Activities

"{"
"\"name\":\"Need Activities\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"Need Work?\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"got Job already?\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"hasWorkAlready\""
"},"
"{"
"\"name\":\"no Money?\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"gotNoMoney\""
"},"
"{"
"\"name\":\"go to Work now!\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"goWork\""
"}]"
"},"
"{"
"\"name\":\"look for work\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"findWork\""
"},"
"{"
"\"name\":\"look for lower level work\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"findLowerJob\""
"},"

"{"
"\"name\":\"cant find work\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"noJobFound\""
"}]"
"},"

// 3rd item

"{"
"\"name\":\"Want Activities\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"Upgrade?\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"Can upgrade house?\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"is there a house to upgrade?\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"isHungry\""
"},"

"{"
"\"name\":\"can I get out of squeeze house?\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"noFood\""
"}]"
"},"
"{"
"\"name\":\"Can upgrade job?\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"Can my Edu Level match the Job Level?\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"buyFood\""
"},"
"{"
"\"name\":\"Get Job\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"eatFood\""
"}]"
"}]"
"},"

"{"
"\"name\":\"Leisure?\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"Work Event\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"To go or not to go?\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"randEvent\""
"},"
"{"
"\"name\":\"Go Work\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"goWork\""
"}]"
"},"

"{"
"\"name\":\"Commerce Event\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"To go or not to go?\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"randEvent\""
"},"
"{"
"\"name\":\"Go Shop\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"findShop\""
"}]"
"},"

"{"
"\"name\":\"Go to Social\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"To go or not to go?\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"randEvent\""
"},"
"{"
"\"name\":\"Go to party\","
"\"type\":\"behaviour\","
"\"file_name\":\"citizenbehavior.lua\","
"\"func_name\":\"findSocial\""
"}]"
"}]"
"}]"
"}]"
"}";
#endif