//
//  builderCFG.h
//  PopulationTest
//
//  Created by Serious Games on 15/4/13.
//
//

#ifndef PopulationTest_builderCFG_h
#define PopulationTest_builderCFG_h

std::string builderDefaults =
"{\"name\":\"root\","
"\"default_happiness\":\"50\","
"\"default_money\":\"200\","
"\"default_loyalty\":\"50\","
"\"default_education_level\":\"1\","
"\"default_move_range\":\"20\","
"\"default_intelligence\":\"50\","
"\"default_social\":\"50\","
"\"default_energy\":\"100\","
"\"default_exp_level1\":\"100\","
"\"default_exp_level2\":\"120\","
"\"default_exp_level3\":\"140\","
"\"default_exp_level4\":\"160\","
"\"default_exp_level5\":\"0\","
"\"spawn_cost\":\"500\""
"}";

std::string builderRequirements =
"{\"name\":\"builder\","
"\"required_loyalty\":\"50\","
"\"required_education_level\":\"1\","
"\"required_intelligence\":\"50\","
"\"required_social\":\"50\""
"}";



std::string builderConfig =
"{\"name\":\"root\","
"\"type\":\"sequence\","
"\"items\":"

// 1st item - Need to get a House

"[{"
"\"name\":\"I need a Home\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"I don't have a house?\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"hasNoHouse\""
"},"

"{"
"\"name\":\"Find a House\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"buyVacantHouse\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"buyVacantHouse\""
"},"

"{"
"\"name\":\"SqueezeHouse\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"squeezeHouse\""
"},"

"{"
"\"name\":\"No House!\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"gotNoHouseWarning\""
"}]"
"}]"
"},"

// 2nd item - the Need to do Activities

"{"
"\"name\":\"Need Activities\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"Need to Work?\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"got Job already?\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"hasWorkAlready\""
"},"
"{"
"\"name\":\"no Money?\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"gotNoMoney\""
"},"
"{"
"\"name\":\"go to Work now!\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"goWork\""
"}]"
"},"
"{"
"\"name\":\"Need to find Job!\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"look for work\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"gotNoWork\""
"},"
"{"
"\"name\":\"look for work\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"findWork\""
"},"
"{"
"\"name\":\"look for lower level work\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"findLowerJob\""
"},"
"{"
"\"name\":\"cant find work\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"noJobFound\""
"}]"
"},"
"{"
"\"name\":\"No Urgent Needs\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"noNeedActivity\""
"}]"
"},"

// 3rd item

"{"
"\"name\":\"Want Activities\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"Upgrade?\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"Can upgrade house?\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"is there a house to upgrade?\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"isSqueezingHouse\""
"},"

"{"
"\"name\":\"can I get out of squeeze house?\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"upgradeHouse\""
"}]"
"},"
"{"
"\"name\":\"Can upgrade class?\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"Have I reach max class level?\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"isMaxClass\""
"},"
"{"
"\"name\":\"Upgrade to new class\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"upgradeClass\""
"}]"
"},"
"{"
"\"name\":\"Can upgrade Job?\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"Can my current job match my edu level?\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"isJobMatching\""
"},"
"{"
"\"name\":\"Get better Job\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"upgradeJob\""
"}]"
"}]"
"},"

"{"
"\"name\":\"Leisure?\","
"\"type\":\"sequence\","
"\"items\":"
"[{"
"\"name\":\"Work Event\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"To go or not to go?\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"randEvent\""
"},"
"{"
"\"name\":\"Go Work\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"goWork\""
"}]"
"},"

"{"
"\"name\":\"Commerce Event\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"To go or not to go?\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"randEvent\""
"},"
"{"
"\"name\":\"Go Shop\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"findShop\""
"}]"
"},"

/*                "{"
 "\"name\":\"Go to Social\","
 "\"type\":\"selector\","
 "\"items\":"
 "[{"
 "\"name\":\"To go or not to go?\","
 "\"type\":\"behaviour\","
 "\"file_name\":\"builderbehavior.lua\","
 "\"func_name\":\"randEvent\""
 "},"
 "{"
 "\"name\":\"Go to party\","
 "\"type\":\"behaviour\","
 "\"file_name\":\"builderbehavior.lua\","
 "\"func_name\":\"findSocial\""
 "}]"
 "}," */
"{"
"\"name\":\"SocialInteraction\","
"\"type\":\"selector\","
"\"items\":"
"[{"
"\"name\":\"To socially interact?\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"checkInteract\""
"},"
"{"
"\"name\":\"Trigger social interaction\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"goInteract\""
"}]"
"},"

"{"
"\"name\":\"Go Wander\","
"\"type\":\"behaviour\","
"\"file_name\":\"builderbehavior.lua\","
"\"func_name\":\"jalanJalan\""
"}]"
"}]"
"}]"
"}";

#endif
