//
//  JobsInGame.h
//  PopulationTest
//
//  Created by Serious Games on 6/5/13.
//
//

#ifndef PopulationTest_JobsInGame_h
#define PopulationTest_JobsInGame_h

std::string AllJobs =
"{\"name\":\"root\","
    "\"items\":"
    "[{"
        "\"job_name\":\"farmer\","
        "\"job_edlevel\":1,"
        "\"job_spriteclass\":\"farmer\","
        "\"job_monthlypay\":10,"
        "\"job_energycost\":10,"
        "\"job_expgain\":10,"
        "\"job_mod_int\":1,"
        "\"job_mod_soc\":5,"
        "\"job_mod_loy\":10,"
        "\"job_mod_hap\":5"
     "},"
    "{"
        "\"job_name\":\"potter\","
        "\"job_edlevel\":3,"
        "\"job_spriteclass\":\"farmer\","
        "\"job_monthlypay\":20,"
        "\"job_energycost\":10,"
        "\"job_expgain\":15,"
        "\"job_mod_int\":1,"
        "\"job_mod_soc\":5,"
        "\"job_mod_loy\":10,"
        "\"job_mod_hap\":5"
    "},"
    "{"
        "\"job_name\":\"miner\","
        "\"job_edlevel\":1,"
        "\"job_spriteclass\":\"farmer\","
        "\"job_monthlypay\":10,"
        "\"job_energycost\":10,"
        "\"job_expgain\":10,"
        "\"job_mod_int\":1,"
        "\"job_mod_soc\":5,"
        "\"job_mod_loy\":10,"
        "\"job_mod_hap\":5"
    "},"
     "{"
        "\"job_name\":\"teacher\","
        "\"job_edlevel\":11,"
        "\"job_spriteclass\":\"researcher\","
        "\"job_monthlypay\":100,"
        "\"job_energycost\":10,"
        "\"job_expgain\":10,"
        "\"job_mod_int\":10,"
        "\"job_mod_soc\":1,"
        "\"job_mod_loy\":1,"
        "\"job_mod_hap\":5"
    "},"

    "{"
        "\"job_name\":\"researcher\","
        "\"job_edlevel\":13,"
        "\"job_spriteclass\":\"researcher\","
        "\"job_monthlypay\":100,"
        "\"job_energycost\":10,"
        "\"job_expgain\":10,"
        "\"job_mod_int\":10,"
        "\"job_mod_soc\":1,"
        "\"job_mod_loy\":1,"
        "\"job_mod_hap\":5"
    "},"

    "{"
        "\"job_name\":\"merchant\","
        "\"job_edlevel\":5,"
        "\"job_spriteclass\":\"merchant\","
        "\"job_monthlypay\":10,"
        "\"job_energycost\":10,"
        "\"job_expgain\":10,"
        "\"job_mod_int\":5,"
        "\"job_mod_soc\":5,"
        "\"job_mod_loy\":1,"
        "\"job_mod_hap\":10"
    "}]"
"}";
#endif
