//
//  Tutorial.h
//  PopulationTest
//
//  Created by Serious Games on 4/6/13.
//
//

#ifndef PopulationTest_Tutorial_h
#define PopulationTest_Tutorial_h
std::string tutorialOrder =
"{\"name\":\"root\","
"\"items\":"
    "[{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"Welcome to the game!\","
        "\"wait_action\":\"alert\","
        "\"wait_targettype\":\"clicked\","
        "\"wait_content\":\"\","
        "\"post_action\":\"\","
        "\"post_targettype\":\"\","
        "\"post_content\":\"\""
    "},"

    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"You have a homeless resident.\","
        "\"wait_action\":\"alert\","
        "\"wait_targettype\":\"clicked\","
        "\"wait_content\":\"\","
        "\"post_action\":\"\","
        "\"post_targettype\":\"\","
        "\"post_content\":\"\""
        "},"

    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"Build a house to cater to their needs. Click on the Menu and select Build\","
        "\"wait_action\":\"constructioncomplete\","
        "\"wait_targettype\":\"building\","
        "\"wait_content\":\"HOUSING\","
        "\"post_action\":\"makebuildable\","
        "\"post_targettype\":\"AMENITY\","
        "\"post_content\":\"Bee Farm\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"Good. Now they need more jobs, build more Amenity to provide jobs.\","
        "\"wait_action\":\"constructioncomplete\","
        "\"wait_targettype\":\"building\","
        "\"wait_content\":\"AMENITY\","
        "\"post_action\":\"system\","
        "\"post_targettype\":\"spawning\","
        "\"post_content\":\"on\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"Good. Your residents are all nice and settled.\","
        "\"wait_action\":\"\","
        "\"wait_targettype\":\"\","
        "\"wait_content\":\"\","
        "\"post_action\":\"spawn\","
        "\"post_targettype\":\"mayan\","
        "\"post_content\":\"farmer\""
    "},"
    "{"
        "\"pre_action\":\"system\","
        "\"pre_targettype\":\"researchmenu\","
        "\"pre_content\":\"enable\","
        "\"wait_action\":\"count\","
        "\"wait_targettype\":\"population\","
        "\"wait_content\":\"4\","
        "\"post_action\":\"spawn\","
        "\"post_targettype\":\"mayan\","
        "\"post_content\":\"merchant\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"hint\","
        "\"pre_content\":\"A Merchant seems to be arriving.\","
        "\"wait_action\":\"spawncomplete\","
        "\"wait_targettype\":\"mayan\","
        "\"wait_content\":\"merchant\","
        "\"post_action\":\"system\","
        "\"post_targettype\":\"spawning\","
        "\"post_content\":\"off\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"The Research menu is now available.\","
        "\"wait_action\":\"\","
        "\"wait_targettype\":\"\","
        "\"wait_content\":\"\","
        "\"post_action\":\"makeresearchable\","
        "\"post_targettype\":\"COMMERCE\","
        "\"post_content\":\"Stone Refinery\""
    "},"

    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"Merchants work best in Commerce building. Research on a Commerce facility in the Research menu.\","
        "\"wait_action\":\"researchcomplete\","
        "\"wait_targettype\":\"building\","
        "\"wait_content\":\"COMMERCE\","
        "\"post_action\":\"message\","
        "\"post_targettype\":\"hint\","
        "\"post_content\":\"Research complete.\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"Now you can select a Commerce building to build in your build menu.\","
        "\"wait_action\":\"constructioncomplete\","
        "\"wait_targettype\":\"building\","
        "\"wait_content\":\"COMMERCE\","
        "\"post_action\":\"makeresearchable\","
        "\"post_targettype\":\"EDUCATION\","
        "\"post_content\":\"Stone Tablet Store\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"Our people need education. Research and build an Education building.\","
        "\"wait_action\":\"researchcomplete\","
        "\"wait_targettype\":\"building\","
        "\"wait_content\":\"EDUCATION\","
        "\"post_action\":\"system\","
        "\"post_targettype\":\"policymenu\","
        "\"post_content\":\"enable\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"hint\","
        "\"pre_content\":\"The Policy menu is now available.\","
        "\"wait_action\":\"constructioncomplete\","
        "\"wait_targettype\":\"building\","
        "\"wait_content\":\"EDUCATION\","
        "\"post_action\":\"system\","
        "\"post_targettype\":\"importalienresearcher\","
        "\"post_content\":\"enable\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"No one is qualified to work in the Stone Tablet Store. Use Policy to import an Alien Researcher\","
        "\"wait_action\":\"spawncomplete\","
        "\"wait_targettype\":\"alien\","
        "\"wait_content\":\"researcher\","
        "\"post_action\":\"makeresearchable\","
        "\"post_targettype\":\"SOCIAL\","
        "\"post_content\":\"City Centre\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"hint\","
        "\"pre_content\":\"A new building is available for research.\","
        "\"wait_action\":\"hint\","
        "\"wait_targettype\":\"timeout\","
        "\"wait_content\":\"\","
        "\"post_action\":\"\","
        "\"post_targettype\":\"\","
        "\"post_content\":\"\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"The locals feel threatened by the presence of an Xenos. Build a Social gathering place to ease the friction.\","
        "\"wait_action\":\"constructioncomplete\","
        "\"wait_targettype\":\"building\","
        "\"wait_content\":\"SOCIAL\","
        "\"post_action\":\"\","
        "\"post_targettype\":\"\","
        "\"post_content\":\"\""
    "},"
    "{"
        "\"pre_action\":\"message\","
        "\"pre_targettype\":\"alert\","
        "\"pre_content\":\"Tutorial Complete.\","
        "\"wait_action\":\"alert\","
        "\"wait_targettype\":\"clicked\","
        "\"wait_content\":\"\","
        "\"post_action\":\"system\","
        "\"post_targettype\":\"spawning\","
        "\"post_content\":\"on\""
    "}]"

"}";

#endif
